import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import { createClient } from '@libsql/client';

try {
  const envContent = fs.readFileSync('.env', 'utf8');
  envContent.split('\n').forEach(line => {
    const parts = line.split('=');
    if (parts.length >= 2 && parts[0].trim() && !process.env[parts[0].trim()]) {
      process.env[parts[0].trim()] = parts.slice(1).join('=').trim();
    }
  });
} catch (e) {}

const makeVariants = (basePrice: number) => JSON.stringify([
  { weightG: 500, price: basePrice, isDefault: true },
  { weightG: 1000, price: Math.round(basePrice * 1.85), isDefault: false },
  { weightG: 1500, price: Math.round(basePrice * 2.7), isDefault: false },
  { weightG: 2000, price: Math.round(basePrice * 3.5), isDefault: false },
]);

const all23Products = [
  {
    id: 'cake_1',
    name: 'Tender Coconut Dream Cake',
    slug: 'tender-coconut-dream-cake',
    description: 'Signature Trivandrum delicacy made with fresh Elaneer (tender coconut pulp), fluffy coconut cream, and soft vanilla sponge.',
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80']),
    category: 'Kerala Specialities',
    baseWeightG: 500,
    basePrice: 650,
    variants: makeVariants(650),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 142,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_2',
    name: 'Belgian Chocolate Truffle Cake',
    slug: 'belgian-chocolate-truffle-cake',
    description: 'Rich 60% dark Belgian chocolate ganache layered between moist cocoa sponge. Smooth, glossy finish topped with hand-carved truffle curls.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 700,
    variants: makeVariants(700),
    isAvailable: 1,
    isFeatured: 1,
    featuredOrder: 1,
    orderCount: 198,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_3',
    name: 'Nutella Hazelnut Crunch',
    slug: 'nutella-hazelnut-crunch',
    description: 'Irresistible Nutella cream layers interspersed with toasted hazelnuts and crunchy wafer pearls on a rich chocolate sponge.',
    imageUrl: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 800,
    variants: makeVariants(800),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 165,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_4',
    name: 'Classic Red Velvet Cream Cheese',
    slug: 'classic-red-velvet-cream-cheese',
    description: 'Traditional crimson velvet sponge with subtle cocoa undertones, layered with rich imported cream cheese frosting.',
    imageUrl: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=800&q=80']),
    category: 'Signature Cakes',
    baseWeightG: 500,
    basePrice: 750,
    variants: makeVariants(750),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 110,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_5',
    name: 'Fresh Alphonso Mango Gateau',
    slug: 'fresh-alphonso-mango-gateau',
    description: 'Seasonal delight loaded with real Alphonso mango pulp, light whipped cream, and tender vanilla sponge.',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80']),
    category: 'Fresh Fruit & Berry',
    baseWeightG: 500,
    basePrice: 700,
    variants: makeVariants(700),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 88,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_6',
    name: 'New York Baked Blueberry Cheesecake',
    slug: 'new-york-baked-blueberry-cheesecake',
    description: 'Slow-baked creamy cheesecake on a buttery Graham cracker crust, smothered with wild blueberry compote.',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80']),
    category: 'Premium Cheesecakes',
    baseWeightG: 500,
    basePrice: 950,
    variants: makeVariants(950),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 76,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_7',
    name: 'Lotus Biscoff Speculoos Cake',
    slug: 'lotus-biscoff-speculoos-cake',
    description: 'Decadent layers of caramelized Biscoff cookie butter cream, crunchy cookie crumbs, and soft brown sugar sponge.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80']),
    category: 'Signature Cakes',
    baseWeightG: 500,
    basePrice: 850,
    variants: makeVariants(850),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 94,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_8',
    name: 'Black Forest Royale',
    slug: 'black-forest-royale',
    description: 'Classic Kirsch-soaked chocolate sponge filled with sour cherries and whipped cream, coated in chocolate shavings.',
    imageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 600,
    variants: makeVariants(600),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 130,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_9',
    name: 'Salted Caramel Butterscotch Crunch',
    slug: 'salted-caramel-butterscotch-crunch',
    description: 'Golden butterscotch sponge layers filled with house-made salted caramel drip, praline crunch, and whipped butter cream.',
    imageUrl: 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80']),
    category: 'Signature Cakes',
    baseWeightG: 500,
    basePrice: 750,
    variants: makeVariants(750),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 64,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_10',
    name: 'Pistachio Saffron Cardamom Cake',
    slug: 'pistachio-saffron-cardamom-cake',
    description: 'Authentic royal Indian flavors featuring real Kashmiri saffron, crushed roasted pistachios, and aromatic green cardamom cream.',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80']),
    category: 'Kerala Specialities',
    baseWeightG: 500,
    basePrice: 850,
    variants: makeVariants(850),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 52,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_11',
    name: 'Triple Chocolate Fudge Overload',
    slug: 'triple-chocolate-fudge-overload',
    description: 'Ultimate chocolate lover dream featuring milk chocolate mousse, dark fudge ganache, and white chocolate curls on cocoa sponge.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 780,
    variants: makeVariants(780),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 115,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_12',
    name: 'Fresh Strawberry Shortcake',
    slug: 'fresh-strawberry-shortcake',
    description: 'Fluffy light vanilla sponge layers overflowing with fresh strawberry slices and sweet whipped cream frosting.',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80']),
    category: 'Fresh Fruit & Berry',
    baseWeightG: 500,
    basePrice: 720,
    variants: makeVariants(720),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 79,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_13',
    name: 'San Sebastian Burnt Basque Cheesecake',
    slug: 'san-sebastian-burnt-basque-cheesecake',
    description: 'Crustless Spanish cheesecake baked at high temperature for a caramelized top and ultra-creamy melting center.',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80']),
    category: 'Premium Cheesecakes',
    baseWeightG: 500,
    basePrice: 980,
    variants: makeVariants(980),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 48,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_14',
    name: 'Rose Falooda Royal Celebration Cake',
    slug: 'rose-falooda-royal-celebration-cake',
    description: 'Infused with fragrant rose water, sabja seeds, and vermicelli jelly cream layers topped with crushed dry fruits.',
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80']),
    category: 'Kerala Specialities',
    baseWeightG: 500,
    basePrice: 790,
    variants: makeVariants(790),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 41,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_15',
    name: 'White Chocolate Raspberry Delight',
    slug: 'white-chocolate-raspberry-delight',
    description: 'Creamy Swiss white chocolate ganache matched with tangy tart raspberry compote between velvet butter sponge layers.',
    imageUrl: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=800&q=80']),
    category: 'Fresh Fruit & Berry',
    baseWeightG: 500,
    basePrice: 760,
    variants: makeVariants(760),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 67,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_16',
    name: 'Ferrero Rocher Hazelnut Drip Cake',
    slug: 'ferrero-rocher-hazelnut-drip-cake',
    description: 'Crown of golden Ferrero Rocher chocolates over dark chocolate ganache drip, filled with hazelnut praline buttercream.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 890,
    variants: makeVariants(890),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 132,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_17',
    name: 'Tiramisu Mascarpone Espresso Cake',
    slug: 'tiramisu-mascarpone-espresso-cake',
    description: 'Italian style coffee-soaked sponge layered with whipped mascarpone cream and dusted with dark Dutch cocoa powder.',
    imageUrl: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=800&q=80']),
    category: 'Signature Cakes',
    baseWeightG: 500,
    basePrice: 820,
    variants: makeVariants(820),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 85,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_18',
    name: 'Custom Two-Tier Floral Birthday Cake',
    slug: 'custom-two-tier-floral-birthday-cake',
    description: 'Stunning 2-tier custom celebration cake with handcrafted edible fondant flowers and personalized gold name topper.',
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80']),
    category: 'Custom Occasion Cakes',
    baseWeightG: 1000,
    basePrice: 1450,
    variants: makeVariants(1450),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 39,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_19',
    name: 'Pistachio Matcha Cream Cake',
    slug: 'pistachio-matcha-cream-cake',
    description: 'Japanese ceremonial grade matcha sponge infused with silky pistachio cream and topped with crushed roasted pistachios.',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80']),
    category: 'Signature Cakes',
    baseWeightG: 500,
    basePrice: 820,
    variants: makeVariants(820),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 58,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_20',
    name: 'Choco Vanilla Swirl Delight',
    slug: 'choco-vanilla-swirl-delight',
    description: 'Dual layered dark chocolate and Madagascar vanilla bean sponge frosted with marbled chocolate buttercream.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 680,
    variants: makeVariants(680),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 92,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_21',
    name: 'Kottayam Passion Fruit Bliss',
    slug: 'kottayam-passion-fruit-bliss',
    description: 'Tangy fresh passion fruit glaze over moist vanilla bean cake, filled with passion fruit curd and white chocolate mousse.',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80']),
    category: 'Fresh Fruit & Berry',
    baseWeightG: 500,
    basePrice: 740,
    variants: makeVariants(740),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 63,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_22',
    name: 'Rich Dark Forest Cherry Fudge',
    slug: 'rich-dark-forest-cherry-fudge',
    description: 'Moist cocoa sponge steeped in black cherry syrup, filled with dark chocolate fudge and maraschino cherries.',
    imageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80']),
    category: 'Chocolate & Truffle',
    baseWeightG: 500,
    basePrice: 760,
    variants: makeVariants(760),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 104,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cake_23',
    name: 'Royal Honey Almond Crunch Cake',
    slug: 'royal-honey-almond-crunch-cake',
    description: 'Pure Wayanad wild honey soaked sponge topped with caramelized sliced almonds and diplomat vanilla cream.',
    imageUrl: 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80',
    images: JSON.stringify(['https://images.unsplash.com/photo-1542826438-bd32f43d626f?auto=format&fit=crop&w=800&q=80']),
    category: 'Kerala Specialities',
    baseWeightG: 500,
    basePrice: 800,
    variants: makeVariants(800),
    isAvailable: 1,
    isFeatured: 0,
    featuredOrder: 0,
    orderCount: 71,
    createdAt: new Date().toISOString(),
  },
];

async function seedBoth() {
  // 1. Local SQLite DB
  const localDbPath = path.join(process.cwd(), 'data', 'myhomelycakes.db');
  console.log('Seeding local SQLite DB at:', localDbPath);
  const sqlite = new Database(localDbPath);
  
  const insertStmt = sqlite.prepare(`
    INSERT OR REPLACE INTO products (id, name, slug, description, image_url, images, category, base_weight_g, base_price, variants, is_available, is_featured, featured_order, order_count, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  for (const p of all23Products) {
    insertStmt.run(
      p.id, p.name, p.slug, p.description, p.imageUrl, p.images, p.category, p.baseWeightG, p.basePrice, p.variants, p.isAvailable, p.isFeatured, p.featuredOrder, p.orderCount, p.createdAt
    );
  }
  console.log('✅ Local SQLite DB populated with all 23 products.');

  // 2. Turso Cloud DB (if configured)
  const tursoUrl = process.env.TURSO_DATABASE_URL;
  const tursoAuthToken = process.env.TURSO_AUTH_TOKEN;
  if (tursoUrl && tursoAuthToken) {
    console.log('Seeding Turso Cloud DB at:', tursoUrl);
    const client = createClient({ url: tursoUrl, authToken: tursoAuthToken });
    for (const p of all23Products) {
      await client.execute({
        sql: `INSERT OR REPLACE INTO products (id, name, slug, description, image_url, images, category, base_weight_g, base_price, variants, is_available, is_featured, featured_order, order_count, created_at)
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        args: [p.id, p.name, p.slug, p.description, p.imageUrl, p.images, p.category, p.baseWeightG, p.basePrice, p.variants, p.isAvailable, p.isFeatured, p.featuredOrder, p.orderCount, p.createdAt]
      });
    }
    console.log('✅ Turso Cloud DB populated with all 23 products.');
  }

  console.log('✨ Synchronization complete!');
  process.exit(0);
}

seedBoth().catch(err => {
  console.error('Sync failed:', err);
  process.exit(1);
});
